<a href="https://colab.research.google.com/github/carolynemusyoka95-spec/spatial-shine-hub/blob/main/Datecleaning_transformatiuion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [13]:
import pandas as pd

In [15]:
#importing dataset-the kenyan hotel csv from my drive
df_ke_hotels = pd.read_csv("/content/drive/MyDrive/python_data_cleaning/kenyan_hotels2.csv")
df_ke_hotels.head()

,booking_id,hotel_name,price_per_night,nights_stayed,customer_rating,check_in_date,check_out_date,booking_timestamp,last_updated
0,1,Nairobi Grand Hotel,NaN,ten,filled_placeholder,filled_placeholder,10/06/2024,2024/09/12,2026-04-04 10:45:04
1,2,Nairobi Grand Hotel,NaN,filled_placeholder,filled_placeholder,filled_placeholder,07/03/2022,2022-07-14 00:00:00,2026-04-04 10:45:04
2,3,Nairobi Grand Hotel,KES 15341.64,4,2.246,2022-11-07,06/24/2025,2022-01-12 00:00:00,2026-04-04 10:45:04
3,4,Savannah Lodge,filled_placeholder,filled_placeholder,6,15/11/2023,filled_placeholder,28/10/2025 00:00,2026-04-04 10:45:04+03:00
4,5,Nairobi Grand Hotel,unknown,10,filled_placeholder,filled_placeholder,26-10-2022,not_a_date,2026-04-04 10:45:04+03:00

In [ ]:
#Cleaning and transforming dates
#check in date
#check out date
#Booking timestamp

In [16]:
# first inspect your dataset to understand the data types/ structure--any missing values, data types are correct, which columns needs cleaning and size of dtatsedt
df_ke_hotels. info ()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   booking_id         500 non-null    int64
 1   hotel_name         500 non-null    object
 2   price_per_night    312 non-null    object
 3   nights_stayed      367 non-null    object
 4   customer_rating    450 non-null    object
 5   check_in_date      450 non-null    object
 6   check_out_date     450 non-null    object
 7   booking_timestamp  450 non-null    object
 8   last_updated       450 non-null    object
dtypes: int64(1), object(8)
memory usage: 35.3+ KB

In [17]:
df_ke_hotels [['check_in_date', 'check_out_date', 'booking_timestamp']].head(10)

        check_in_date      check_out_date    booking_timestamp
0  filled_placeholder          10/06/2024           2024/09/12
1  filled_placeholder          07/03/2022  2022-07-14 00:00:00
2          2022-11-07          06/24/2025  2022-01-12 00:00:00
3          15/11/2023  filled_placeholder     28/10/2025 00:00
4  filled_placeholder          26-10-2022           not_a_date
5          07-05-2022          04/03/2025     05/06/2025 00:00
6        invalid_date          02-10-2022     07/12/2023 00:00
7          09-20-2024          11/02/2023           2025/08/25
8          14/08/2025          32/13/2023           2025/04/21
9        invalid_date          07-10-2024           2022/11/01

In [18]:
# part 1: cleaning and transforming the check_in_date column

#cleaning part
#standardize the ddelimiters-like use hypens in all the dates and replace or remove any slashes
df_ke_hotels['check_in_date_cleaned']=df_ke_hotels['check_in_date'].str.replace("/", "-", regex=True)

In [23]:
#replace the check in. date from string (object) to date time
df_ke_hotels['check_in_date_cleaned']=pd.to_datetime(df_ke_hotels['check_in_date_cleaned'],
 errors='coerce',
format ='mixed', # date formnat is mixed if yes follow up wqith dayfirst =true, otherwise if noit mixed omit the format and dayfirst
                                                     # during inspection, I noticed that the check_in_date column has multiple formats.
                      #So I will use format = 'mixed' to handle this issue.
                      # If you are sure that all the dates in the column are in the same format,
                      # you can specify that format instead of using 'mixed'
                      # examples: %Y-%m-%d, %d-%m-%Y, %m/%d/%Y,
 dayfirst=True) # during inspection when you see format as %Y-%m-%d, no need to use dayfirst = True
df_ke_hotels['check_in_date_cleaned'].head(10) # all date format are standardized in y/m/d and rest of errors coerced into NAT

0          NaT
1          NaT
2   2022-11-07
3   2023-11-15
4          NaT
5   2022-05-07
6          NaT
7   2024-09-20
8   2025-08-14
9          NaT
Name: check_in_date_cleaned, dtype: datetime64[ns]

In [25]:
df_ke_hotels.info() # check_in_date_cleaned column has been added

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   booking_id             500 non-null    int64
 1   hotel_name             500 non-null    object
 2   price_per_night        312 non-null    object
 3   nights_stayed          367 non-null    object
 4   customer_rating        450 non-null    object
 5   check_in_date          450 non-null    object
 6   check_out_date         450 non-null    object
 7   booking_timestamp      450 non-null    object
 8   last_updated           450 non-null    object
 9   check_in_date_cleaned  302 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(8)
memory usage: 39.2+ KB

In [39]:
# the transformation part

# find check in year
df_ke_hotels['check_in _year']=df_ke_hotels['check_in_date_cleaned'].dt.year

# find check in month id and check in month name
df_ke_hotels['check_in _month_id']=df_ke_hotels['check_in_date_cleaned'].dt.month

df_ke_hotels['check_in _month_name']=df_ke_hotels['check_in_date_cleaned'].dt.month_name()

## find check in quarter
df_ke_hotels['check_in _quarter']=df_ke_hotels['check_in_date_cleaned'].dt.quarter
# find check in quarter
# find check in day of the month, day name, day of the week (monday=o,1,2 etc)
df_ke_hotels['check_in_day_of month']=df_ke_hotels['check_in_date_cleaned'].dt.day
df_ke_hotels['check_in_day_name']=df_ke_hotels['check_in_date_cleaned'].dt.day_name()
df_ke_hotels['check_in_day_of_week']=df_ke_hotels['check_in_date_cleaned'].dt.dayofweek
#

In [41]:
# using day of week we can create a column "is_weekend" to identify whether it's true a day is on weekend or false
df_ke_hotels['check_in_is_weekend'] =df_ke_hotels['check_in_day_of_week'].isin([5,6])
df_ke_hotels.head (15)

,booking_id,hotel_name,price_per_night,nights_stayed,customer_rating,check_in_date,check_out_date,booking_timestamp,last_updated,check_in_date_cleaned,check_in _year,check_in _month_id,check_in _month_name,check_in _quarter,check_in_day_of month,check_in_day_name,check_in_day_of week,check_in_day_of_week,check_in_is_weekend
0,1,Nairobi Grand Hotel,NaN,ten,filled_placeholder,filled_placeholder,10/06/2024,2024/09/12,2026-04-04 10:45:04,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1,2,Nairobi Grand Hotel,NaN,filled_placeholder,filled_placeholder,filled_placeholder,07/03/2022,2022-07-14 00:00:00,2026-04-04 10:45:04,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
2,3,Nairobi Grand Hotel,KES 15341.64,4,2.246,2022-11-07,06/24/2025,2022-01-12 00:00:00,2026-04-04 10:45:04,2022-11-07,2022.0,11.0,November,4.0,7.0,Monday,0.0,0.0,False
3,4,Savannah Lodge,filled_placeholder,filled_placeholder,6,15/11/2023,filled_placeholder,28/10/2025 00:00,2026-04-04 10:45:04+03:00,2023-11-15,2023.0,11.0,November,4.0,15.0,Wednesday,2.0,2.0,False
4,5,Nairobi Grand Hotel,unknown,10,filled_placeholder,filled_placeholder,26-10-2022,not_a_date,2026-04-04 10:45:04+03:00,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
5,6,Nairobi Grand Hotel,KES 9820.85,-2,4.567,07-05-2022,04/03/2025,05/06/2025 00:00,filled_placeholder,2022-05-07,2022.0,5.0,May,2.0,7.0,Saturday,5.0,5.0,True
6,7,Savannah Lodge,filled_placeholder,-2,filled_placeholder,invalid_date,02-10-2022,07/12/2023 00:00,2026-04-04 10:45:04+03:00,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
7,8,Savannah Lodge,unknown,ten,1.762,09-20-2024,11/02/2023,2025/08/25,2026-04-04 10:45:04,2024-09-20,2024.0,9.0,September,3.0,20.0,Friday,4.0,4.0,False
8,9,Nairobi Grand Hotel,filled_placeholder,-2,filled_placeholder,14/08/2025,32/13/2023,2025/04/21,filled_placeholder,2025-08-14,2025.0,8.0,August,3.0,14.0,Thursday,3.0,3.0,False
9,10,Nairobi Grand Hotel,unknown,ten,filled_placeholder,invalid_date,07-10-2024,2022/11/01,2026-04-04 10:45:04,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
10,11,Coastal Breeze Resort,KES 19395.75,NaN,3.885,2025-12-20,2025/02/14,2022/07/25,2026-04-04 10:45:04+03:00,2025-12-20,2025.0,12.0,December,4.0,20.0,Saturday,5.0,5.0,True
11,12,Coastal Breeze Resort,KES 6326.11,NaN,6,filled_placeholder,32/13/2023,2024-03-31 00:00:00,2026-04-04 10:45:04+03:00,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
12,13,Nairobi Grand Hotel,NaN,9,6,02-17-2025,2023/04/09,filled_placeholder,2026-04-04 10:45:04+03:00,2025-02-17,2025.0,2.0,February,1.0,17.0,Monday,0.0,0.0,False
13,14,Nairobi Grand Hotel,NaN,3,filled_placeholder,24/05/2022,08/20/2025,2022-11-11 00:00:00,2026-04-04 10:45:04+03:00,2022-05-24,2022.0,5.0,May,2.0,24.0,Tuesday,1.0,1.0,False
14,15,Savannah Lodge,unknown,5,bad,2022-03-18,2025/10/25,18/09/2025 00:00,filled_placeholder,2022-03-18,2022.0,3.0,March,1.0,18.0,Friday,4.0,4.0,False

In [82]:
#Assignment ## part 1: cleaning and transforming the bookingtimestamp column
#inspection and understanding the data
df_ke_hotels['booking_timestamp'].unique()
df_ke_hotels.info()
df_ke_hotels['booking_timestamp'].head(20)
#cleaning part
#standardize the ddelimiters-like use hypens in all the dates and replace or remove any slashes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 28 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   booking_id                            500 non-null    int64
 1   hotel_name                            500 non-null    object
 2   price_per_night                       312 non-null    object
 3   nights_stayed                         367 non-null    object
 4   customer_rating                       450 non-null    object
 5   check_in_date                         450 non-null    object
 6   check_out_date                        450 non-null    object
 7   booking_timestamp                     450 non-null    object
 8   last_updated                          450 non-null    object
 9   check_in_date_cleaned                 302 non-null    datetime64[ns]
 10  check_in _year                        302 non-null    float64
 11  check_in _month_id                    302 non-null    float64
 12  check_in _month_name                  302 non-null    object
 13  check_in _quarter                     302 non-null    float64
 14  check_in_day_of month                 302 non-null    float64
 15  check_in_day_name                     302 non-null    object
 16  check_in_day_of week                  302 non-null    float64
 17  check_in_day_of_week                  302 non-null    float64
 18  check_in_is_weekend                   500 non-null    bool
 19  booking_timestamp_cleaned             297 non-null    datetime64[ns]
 20  booking_timestamp_cleaned_year        297 non-null    float64
 21  booking_timestamp_cleaned_month_id    297 non-null    float64
 22  booking_timestamp_cleaned_month_name  297 non-null    object
 23  booking_timestamp_cleaned_quarter     297 non-null    float64
 24  bookings_timestamp_day_of_month       297 non-null    float64
 25  bookings_timestamp_day__name          297 non-null    object
 26  bookings_timestamp_day__of_week       297 non-null    float64
 27  booking_timestamp_cleaned_is_weekend  500 non-null    bool
dtypes: bool(2), datetime64[ns](2), float64(11), int64(1), object(12)
memory usage: 102.7+ KB

0              2024/09/12
1     2022-07-14 00:00:00
2     2022-01-12 00:00:00
3        28/10/2025 00:00
4              not_a_date
5        05/06/2025 00:00
6        07/12/2023 00:00
7              2025/08/25
8              2025/04/21
9              2022/11/01
10             2022/07/25
11    2024-03-31 00:00:00
12     filled_placeholder
13    2022-11-11 00:00:00
14       18/09/2025 00:00
15     filled_placeholder
16       09/06/2024 00:00
17     filled_placeholder
18       09/09/2023 00:00
19       01/09/2022 00:00
Name: booking_timestamp, dtype: object

In [65]:

df_ke_hotels['booking_timestamp'].head(10) #inspecting the booking stamp column --has mixed format, dashes etc

#standardize-standardize the  date delimiters-like use hypens in all the dates and replace or remove any slashes
df_ke_hotels['booking_timestamp_cleaned']= df_ke_hotels['booking_timestamp'].str.replace ("/", "-",regex=True)
#df_ke_hotels['booking_timestamp_cleaned'].head()

0             2024-09-12
1    2022-07-14 00:00:00
2    2022-01-12 00:00:00
3       28-10-2025 00:00
4             not_a_date
Name: booking_timestamp_cleaned, dtype: object

In [74]:
#replace the bookingstamp column from string (object) to date time
df_ke_hotels['booking_timestamp_cleaned']= df_ke_hotels['booking_timestamp'].str.replace ("/", "-", regex=True)
#df_ke_hotels['booking_timestamp_cleaned'].head()
df_ke_hotels['booking_timestamp_cleaned']=pd.to_datetime (df_ke_hotels['booking_timestamp_cleaned'],
  errors='coerce',
  format='mixed',  #date format is mixed so, yes follow up with dayfirst =true
  dayfirst= True) ## during inspection the format arfe not only this  %Y-%m-%d but are m ixed , \thus i  need to use dayfirst = True

df_ke_hotels[['booking_timestamp', 'booking_timestamp_cleaned']].head(8)

     booking_timestamp booking_timestamp_cleaned
0           2024/09/12                2024-09-12
1  2022-07-14 00:00:00                2022-07-14
2  2022-01-12 00:00:00                2022-01-12
3     28/10/2025 00:00                2025-10-28
4           not_a_date                       NaT
5     05/06/2025 00:00                2025-06-05
6     07/12/2023 00:00                2023-12-07
7           2025/08/25                2025-08-25

In [80]:
# the transformation part

# find check in year
df_ke_hotels['booking_timestamp_cleaned_year'] = df_ke_hotels['booking_timestamp_cleaned'].dt.year
#month id
df_ke_hotels['booking_timestamp_cleaned_month_id'] = df_ke_hotels['booking_timestamp_cleaned'].dt.month
#month name
df_ke_hotels['booking_timestamp_cleaned_month_name'] = df_ke_hotels['booking_timestamp_cleaned'].dt.month_name()
#quarter
df_ke_hotels['booking_timestamp_cleaned_quarter'] = df_ke_hotels['booking_timestamp_cleaned'].dt.quarter

# find check in day of the month, day name, day of the week
#find bookings_timesgtamp of the month
df_ke_hotels['bookings_timestamp_day_of_month'] = df_ke_hotels['booking_timestamp_cleaned'].dt.day
df_ke_hotels['bookings_timestamp_day__name'] = df_ke_hotels['booking_timestamp_cleaned'].dt.day_name()
#day of the week
df_ke_hotels['bookings_timestamp_day__of_week'] = df_ke_hotels['booking_timestamp_cleaned'].dt.dayofweek
#is weekend
df_ke_hotels['booking_timestamp_cleaned_is_weekend'] = df_ke_hotels['bookings_timestamp_day__of_week'].isin ([5,6])

df_ke_hotels.head(15)

,booking_id,hotel_name,price_per_night,nights_stayed,customer_rating,check_in_date,check_out_date,booking_timestamp,last_updated,check_in_date_cleaned,...,check_in_is_weekend,booking_timestamp_cleaned,booking_timestamp_cleaned_year,booking_timestamp_cleaned_month_id,booking_timestamp_cleaned_month_name,booking_timestamp_cleaned_quarter,bookings_timestamp_day_of_month,bookings_timestamp_day__name,bookings_timestamp_day__of_week,booking_timestamp_cleaned_is_weekend
0,1,Nairobi Grand Hotel,NaN,ten,filled_placeholder,filled_placeholder,10/06/2024,2024/09/12,2026-04-04 10:45:04,NaT,...,False,2024-09-12,2024.0,9.0,September,3.0,12.0,Thursday,3.0,False
1,2,Nairobi Grand Hotel,NaN,filled_placeholder,filled_placeholder,filled_placeholder,07/03/2022,2022-07-14 00:00:00,2026-04-04 10:45:04,NaT,...,False,2022-07-14,2022.0,7.0,July,3.0,14.0,Thursday,3.0,False
2,3,Nairobi Grand Hotel,KES 15341.64,4,2.246,2022-11-07,06/24/2025,2022-01-12 00:00:00,2026-04-04 10:45:04,2022-11-07,...,False,2022-01-12,2022.0,1.0,January,1.0,12.0,Wednesday,2.0,False
3,4,Savannah Lodge,filled_placeholder,filled_placeholder,6,15/11/2023,filled_placeholder,28/10/2025 00:00,2026-04-04 10:45:04+03:00,2023-11-15,...,False,2025-10-28,2025.0,10.0,October,4.0,28.0,Tuesday,1.0,False
4,5,Nairobi Grand Hotel,unknown,10,filled_placeholder,filled_placeholder,26-10-2022,not_a_date,2026-04-04 10:45:04+03:00,NaT,...,False,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
5,6,Nairobi Grand Hotel,KES 9820.85,-2,4.567,07-05-2022,04/03/2025,05/06/2025 00:00,filled_placeholder,2022-05-07,...,True,2025-06-05,2025.0,6.0,June,2.0,5.0,Thursday,3.0,False
6,7,Savannah Lodge,filled_placeholder,-2,filled_placeholder,invalid_date,02-10-2022,07/12/2023 00:00,2026-04-04 10:45:04+03:00,NaT,...,False,2023-12-07,2023.0,12.0,December,4.0,7.0,Thursday,3.0,False
7,8,Savannah Lodge,unknown,ten,1.762,09-20-2024,11/02/2023,2025/08/25,2026-04-04 10:45:04,2024-09-20,...,False,2025-08-25,2025.0,8.0,August,3.0,25.0,Monday,0.0,False
8,9,Nairobi Grand Hotel,filled_placeholder,-2,filled_placeholder,14/08/2025,32/13/2023,2025/04/21,filled_placeholder,2025-08-14,...,False,2025-04-21,2025.0,4.0,April,2.0,21.0,Monday,0.0,False
9,10,Nairobi Grand Hotel,unknown,ten,filled_placeholder,invalid_date,07-10-2024,2022/11/01,2026-04-04 10:45:04,NaT,...,False,2022-11-01,2022.0,11.0,November,4.0,1.0,Tuesday,1.0,False
10,11,Coastal Breeze Resort,KES 19395.75,NaN,3.885,2025-12-20,2025/02/14,2022/07/25,2026-04-04 10:45:04+03:00,2025-12-20,...,True,2022-07-25,2022.0,7.0,July,3.0,25.0,Monday,0.0,False
11,12,Coastal Breeze Resort,KES 6326.11,NaN,6,filled_placeholder,32/13/2023,2024-03-31 00:00:00,2026-04-04 10:45:04+03:00,NaT,...,False,2024-03-31,2024.0,3.0,March,1.0,31.0,Sunday,6.0,True
12,13,Nairobi Grand Hotel,NaN,9,6,02-17-2025,2023/04/09,filled_placeholder,2026-04-04 10:45:04+03:00,2025-02-17,...,False,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
13,14,Nairobi Grand Hotel,NaN,3,filled_placeholder,24/05/2022,08/20/2025,2022-11-11 00:00:00,2026-04-04 10:45:04+03:00,2022-05-24,...,False,2022-11-11,2022.0,11.0,November,4.0,11.0,Friday,4.0,False
14,15,Savannah Lodge,unknown,5,bad,2022-03-18,2025/10/25,18/09/2025 00:00,filled_placeholder,2022-03-18,...,False,2025-09-18,2025.0,9.0,September,3.0,18.0,Thursday,3.0,False

In [83]:
#final clean
df_ke_hotels.columns

Index(['booking_id', 'hotel_name', 'price_per_night', 'nights_stayed',
       'customer_rating', 'check_in_date', 'check_out_date',
       'booking_timestamp', 'last_updated', 'check_in_date_cleaned',
       'check_in _year', 'check_in _month_id', 'check_in _month_name',
       'check_in _quarter', 'check_in_day_of month', 'check_in_day_name',
       'check_in_day_of week', 'check_in_day_of_week', 'check_in_is_weekend',
       'booking_timestamp_cleaned', 'booking_timestamp_cleaned_year',
       'booking_timestamp_cleaned_month_id',
       'booking_timestamp_cleaned_month_name',
       'booking_timestamp_cleaned_quarter', 'bookings_timestamp_day_of_month',
       'bookings_timestamp_day__name', 'bookings_timestamp_day__of_week',
       'booking_timestamp_cleaned_is_weekend'],
      dtype='object')

In [89]:
df_ke_hotels_clean = df_ke_hotels[['booking_id', 'hotel_name', 'price_per_night', 'nights_stayed','check_in_date_cleaned',
       'check_in _year', 'check_in _month_id', 'check_in _month_name',
       'check_in _quarter', 'check_in_day_of month', 'check_in_day_name',
       'check_in_day_of week', 'check_in_day_of_week', 'check_in_is_weekend',
       'booking_timestamp_cleaned', 'booking_timestamp_cleaned_year',
       'booking_timestamp_cleaned_month_id',
       'booking_timestamp_cleaned_month_name',
       'booking_timestamp_cleaned_quarter', 'bookings_timestamp_day_of_month',
       'bookings_timestamp_day__name', 'bookings_timestamp_day__of_week',
       'booking_timestamp_cleaned_is_weekend']]

In [90]:
# it's time to export the cleaned and transformed dataset to excel
df_ke_hotels_clean.to_excel( r"/content/drive/MyDrive/python_data_cleaning/kenyan_hotels_cleaned_copy.xlsx", index = False)

In [94]:
df_ke_hotels.to_csv("kenyan_hotels_cleaned_'copy.csv")